version: '3'

services:
  frontend:
    build:
      context: ./front
    container_name: react_app
    ports:
      - "3000:3000"   # Exposes React app on localhost:3000
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000  # Points Axios to the backend container
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    container_name: backend_app
    ports:
      - "8000:8000"   # Exposes Backend on localhost:8000
    environment:
      - ENV=development